Add basic auth to artifacts request
avito-tech/Emcee pull request #23
Opened 2021-06-08 12:12 UTC by venigreat

Add a new dictionary to buildArtifacts
for example "hostsTokens": {"host": "token"}

Dictionary values ​​are added to artifact requests if they need authorization

2021-06-09 12:14 UTC, beefon commented on Sources/BuildArtifacts/BuildArtifacts.swift
> +    public let hostsTokens: [String: String]
Let's extend this feature a bit. Can you please rename this to `hostHeaders: [String: [String: String]]` to allow appending an arbitrary HTTP headers to outgoing requests.

2021-06-09 12:15 UTC, beefon requested changes
Thanks for doing this!

2021-06-09 21:30 UTC, beefon commented
You also need to attach your headers to `ResourceLocation.remoteUrl`, otherwise headers won't be applied on workers.

2021-06-10 20:02 UTC, beefon commented
Want to clarify `ResourceLocation`. Emcee uses 'typed' resource locations to make sure you can't pass a [location of an app](https://github.com/avito-tech/Emcee/blob/master/Sources/BuildArtifacts/AppBundleLocation.swift) instead of [xctest bundle location](https://github.com/avito-tech/Emcee/blob/master/Sources/BuildArtifacts/TestBundleLocation.swift), for example. There are other types of resource locations (just a wrappers).

So by saying..

> You also need to attach your headers to `ResourceLocation.remoteUrl`

I meant updating a JSON scheme to add headers to `ResourceLocation.remoteUrl(URL, headers)` case.

Thus, instead of adding headers to [build artifacts](https://github.com/avito-tech/Emcee/blob/master/Sources/BuildArtifacts/BuildArtifacts.swift) model, it is better to add them to [resource location](https://github.com/avito-tech/Emcee/blob/master/Sources/ResourceLocation/ResourceLocation.swift), because individual artifacts potentially may be hosted on different hosts, and Emcee adopters might want to send different headers for different kinds of artifacts. Potentially.

2021-06-10 20:02 UTC, beefon commented
Want to clarify `ResourceLocation`. Emcee uses 'typed' resource locations to make sure you can't pass a [location of an app](https://github.com/avito-tech/Emcee/blob/master/Sources/BuildArtifacts/AppBundleLocation.swift) instead of [xctest bundle location](https://github.com/avito-tech/Emcee/blob/master/Sources/BuildArtifacts/TestBundleLocation.swift), for example. There are other types of resource locations (just a wrappers).

So by saying..

> You also need to attach your headers to `ResourceLocation.remoteUrl`

I meant updating a JSON scheme to add headers to `ResourceLocation.remoteUrl(URL, headers)` case.

Thus, instead of adding headers to [build artifacts](https://github.com/avito-tech/Emcee/blob/master/Sources/BuildArtifacts/BuildArtifacts.swift) model, it is better to add them to [resource location](https://github.com/avito-tech/Emcee/blob/master/Sources/ResourceLocation/ResourceLocation.swift), because individual artifacts potentially may be hosted on different hosts, and Emcee adopters might want to send different headers for different kinds of artifacts. Potentially.

2021-06-11 16:52 UTC, venigreat commented
All comments fixed, all tests is green

2021-06-11 20:32 UTC, beefon approved these changes

2021-06-11 20:32 UTC, beefon commented on Tests/TestArgFileTests/TestArgFileTests.swift
> +                            },
Do you think you can update your PR to support old styled URLs for cases when there are no headers needed?

```
"appBundle": {
    "url": "http://example.com/App.zip#MyApp/MyApp.app",
    "headers": {"x": "y"}
}
```

```
"appBundle": "http://example.com/App.zip#MyApp/MyApp.app"
```

2021-06-11 20:32 UTC, beefon commented on Sources/ResourceLocation/ResourceLocation.swift
> +    public static func from(_ string: String, headers: [String: String] = [:]) throws -> ResourceLocation {
I will think about how we can make this function a bit cleaner after you merge your changes. For now let's leave it as is.

2021-06-11 20:33 UTC, merged

2021-06-11 20:33 UTC, beefon commented
If you want, you can put up another PR with my minor comments.